random_facts = [
    "A shrimp's heart is in its head, which is a terrible design for anyone who thinks with their feelings.",
    "Wombat poop is cube-shaped, meaning they are the only creatures on Earth that literally poop bricks.",
    "A group of flamingos is called a 'flamboyance,' and they absolutely live up to that fabulous name.",
    "The inventor of the Frisbee was turned into a Frisbee after he died, achieving the most bizarre form of immortality.",
    "Scotland's national animal is the unicorn, because of course it is.",
    "Bananas are berries, but strawberries aren't. Your entire fruit salad is a botanical lie.",
    "An ostrich's eye is bigger than its brain, which explains why they are so easily surprised.",
    "It's impossible to hum while holding your nose, a fact you probably just tested.",
    "A single cloud can weigh over a million pounds, making 'on cloud nine' a dangerously heavy place to be.",
    "Otters hold hands when they sleep so they don't float away, setting relationship goals for the entire animal kingdom.",
    "The Eiffel Tower can grow over 6 inches in the summer, proving even landmarks have summer growth spurts.",
    "Cows have best friends and get stressed when they are separated, which is udderly adorable.",
    "Honey never spoils. Your 3,000-year-old Egyptian tomb snack is ready when you are.",
    "There are more possible iterations of a game of chess than there are atoms in the known universe. No pressure.",
    "A crocodile cannot stick its tongue out. It's permanently stuck to the roof of its mouth, which is just rude.",
    "The King of Hearts is the only king in a deck of cards without a mustache. He was clearly a trendsetter.",
    "A snail can sleep for three years straight, which sounds like an amazing weekend.",
    "Most lipstick contains fish scales. You've been kissing fish this whole time.",
    "In Switzerland, it is illegal to own just one guinea pig because they get lonely. It's the law to have a buddy.",
    "A day on Venus is longer than a year on Venus. Talk about a long workday.",
    "Dragonflies have six legs but cannot walk. They're all about that fly life, literally.",
    "Pigs can't look up into the sky, so they'll never know the pure joy of seeing a bird poop on your car.",
    "The sound of a whip cracking is actually a tiny sonic boom because the tip moves faster than the speed of sound.",
    "Octopuses have three hearts. Two pump blood through the gills, and the third is for everything else. It's complicated.",
    "Butterflies taste with their feet, which makes landing on flowers a full culinary experience.",
    "Dolphins give each other names using unique whistles, basically the ocean's version of a group chat.",
    "Your brain is more active at night than during the day. It’s a nocturnal drama queen.",
    "The state of Ohio accepts a hot air balloon as payment for a debt. Good luck finding a cashier.",
    "A 'jiffy' is an actual unit of time: 1/100th of a second. So 'I'll be there in a jiffy' is a bold-faced lie.",
    "Under their fur, polar bears have black skin to better absorb the sun's heat.",
    "Sea lions can dance to a beat, proving they have better rhythm than most of your relatives at a wedding.",
    "Carrots were originally purple until Dutch farmers cultivated them to be orange as a tribute to their royal family.",
    "There are more fake flamingos in the world than real ones. We live in a plastic paradise.",
    "The blob of toothpaste on a toothbrush has a name: a 'nurdle'.",
    "Goats have rectangular pupils, giving them a panoramic view of their surroundings and a slightly demonic look.",
    "The tiny pocket in your jeans was originally designed to hold a pocket watch, not your shattered dreams.",
    "The unicorn is the national animal of Scotland. They're deadly serious about it.",
    "A group of crows is called a 'murder,' which is probably what they're plotting while staring at you.",
    "The human stomach can dissolve razor blades. Do not try this at home. Seriously.",
    "A blue whale's tongue weighs as much as an elephant. It's the ultimate tongue twister.",
    "Ketchup was sold in the 1830s as medicine. 'A spoonful of ketchup helps the medicine go down.'",
    "It rains diamonds on Saturn and Jupiter. The galaxy's most expensive weather forecast.",
    "A group of owls is called a 'parliament,' where they wisely debate whooo's on first.",
    "You can't fold a piece of paper in half more than 7 times. Your muscles are no match for geometry.",
    "The first orange wasn't orange. It was a greenish-yellow hybrid from Southeast Asia.",
    "There are more stars in the universe than grains of sand on all the world's beaches. Chew on that.",
    "Your nose can remember 50,000 different scents, including that one weird smell from your childhood basement.",
    "Armadillos almost always give birth to identical quadruplets.",
    "The Hawaiian alphabet has only 12 letters. It’s the original minimalist language.",
    "All British tanks since 1945 have included tea-making facilities. It’s a tactical necessity.",
    "A flea can jump 350 times its body length. It’s like a human jumping the length of a football field.",
    "Elephants are the only animal that can't jump. They are permanently grounded.",
    "The inventor of the Pringles can is now buried in one. He lived, breathed, and was laid to rest in crisp perfection.",
    "Cap'n Crunch's full name is Horatio Magellan Crunch. He's a naval legend.",
    "The Twitter bird's official name is Larry T. Bird, named after basketball legend Larry Bird.",
    "A giant squid's eyes are the size of basketballs, perfect for seeing your tiny submarine of terror.",
    "Sound doesn't travel in space. It's a silent, cosmic horror movie out there.",
    "Marie Curie's notebooks are still radioactive. You need protective gear just to read her grocery list.",
    "The longest wedding veil was longer than 63 football fields. Talk about a dramatic entrance.",
    "The longest time between two twins being born is 87 days. The second one was fashionably late.",
    "M&M's stands for 'Mars & Murrie,' the last names of the two founders.",
    "Beavers have orange teeth because their enamel contains iron, making them strong enough to chew through wood.",
    "Giraffes have no vocal cords. They communicate through silent, awkward staring contests.",
    "A chicken once lived for 18 months without a head. His name was Mike and he was a legend.",
    "Some cats are allergic to humans. It might not be you, it might be their allergies.",
    "A cockroach can live for a week without its head. It only dies because it can't drink water.",
    "Slugs have four noses, which seems excessive for something that just smells dirt and fear.",
    "The word 'avocado' comes from an Aztec word that also means 'testicle'. Guacamole will never be the same.",
    "The cigarette lighter was invented before the match.",
    "In the 1800s, people used to send each other vinegar-themed 'insult cards' on Valentine's Day.",
    "The first movie to ever show a toilet flushing was Alfred Hitchcock's 'Psycho'. It was a scandal.",
    "You are 1% shorter in the evening than in the morning due to spinal compression. You literally shrink all day.",
    "There is a town in Norway called 'Hell'. And yes, it freezes over in the winter.",
    "A golf ball has an average of 336 dimples. Now you have something to count while you look for it in the woods.",
    "A baby octopus is about the size of a flea when it's born.",
    "The 'Mona Lisa' has no eyebrows because it was the fashion in Renaissance Florence to shave them off.",
    "The LEGO Group is the world's largest tire manufacturer, producing over 300 million tiny tires a year.",
    "A bolt of lightning is five times hotter than the surface of the sun.",
    "In Japan, letting a sumo wrestler make your baby cry is considered good luck.",
    "A cat's brain is more biologically similar to a human brain than a dog's.",
    "The 'dot' over the letter 'i' and 'j' is called a 'tittle'.",
    "If you could drive your car straight up, you would get to space in just over an hour.",
    "Hippopotamus milk is bright pink.",
    "Nintendo was founded in 1889 as a playing card company.",
    "Human teeth are just as strong as shark teeth.",
    "The fingerprints of a koala are so indistinguishable from humans that they have on occasion been confused at a crime scene.",
    "In ancient Egypt, servants were smeared with honey to attract flies away from the pharaoh.",
    "It would take 1,200,000 mosquitoes, all sucking at once, to completely drain the average human of blood.",
    "The ampersand symbol (&) is a condensed version of the Latin word 'et,' which means 'and'.",
    "There's a species of jellyfish that is biologically immortal, basically the Highlander of the sea.",
    "The voices of Mickey and Minnie Mouse were provided by a real-life married couple, Wayne Allwine and Russi Taylor.",
    "A shark is the only fish that can blink with both eyes.",
    "Saudi Arabia imports camels from Australia, which is the ultimate Uno reverse card.",
    "The original name for the search engine Google was 'Backrub'.",
    "The national anthem of Spain has no words.",
    "During your lifetime, you will produce enough saliva to fill two swimming pools.",
    "Maine is the closest U.S. state to Africa.",
    "The Barbie doll's full name is Barbara Millicent Roberts.",
    "In Germany, there's a poodle-shaped building that serves as a museum for poodles.",
]
